### PR TITLE
Add EMDX subnet configuration

### PR DESCRIPTION
**Pull request by afiorenza**

### CODE REVIEW

**Comment by rajranjan0608** [comment]
Looks good to me 👍. Can you also add the explorer info for your subnet, we need that to link successful token drips.

**Comment by afiorenza** [comment]
> Looks good to me +1. Can you also add the explorer info for your subnet, we need that to link successful token drips.

Done! Thanks for your review

**Review by rajranjan0608 — APPROVED** [review]
Awesome! Would be great if you can send 5-10 sEMDX to the following address for testing.

```
0x3EA53fA26b41885cB9149B62f0b7c0BAf76C78D4
```

**Comment by afiorenza** [comment]
> Awesome! Would be great if you can send 5-10 sEMDX to the following address for testing.
> 
> ```
> 0x3EA53fA26b41885cB9149B62f0b7c0BAf76C78D4
> ```

@rajranjan0608  sEMDX sent!

**Comment by maxidev** [comment]
Hey @rajranjan0608 were you able to test it out? thank you!

**Comment by rajranjan0608** [comment]
Hey @maxidev & @afiorenza. EMDX subnet integration should be live at:

https://faucet.avax.network/?subnet=emdx

Feel free to fuel the faucet address with your subnet coins 🚀. Apologies for the delayed response.

Faucet address can be found on the above link or just use the below address:

```
0x2352D20fC81225c8ECD8f6FaA1B37F24FEd450c9
```

**Comment by maxidev** [comment]
> Hey @maxidev & @afiorenza. EMDX subnet integration should be live at:
> 
> https://faucet.avax.network/?subnet=emdx
> 
> Feel free to fuel the faucet address with your subnet coins 🚀. Apologies for the delayed response.
> 
> Faucet address can be found on the above link or just use the below address:
> 
> ```
> 0x2352D20fC81225c8ECD8f6FaA1B37F24FEd450c9
> ```

Hi @rajranjan0608 thank you so much, we see that live but as of now the internal faucet API is returning 0 balance of sEMDX for the faucet address (but it has 100 sEMDX) ready to transfer, not sure if we need to wait the API for updating or maybe we have some technical thing wrong.

Thank you!

**Comment by rajranjan0608** [comment]
@maxidev balance should be reflected as soon as it's transferred. I'm seeing this error in the logs for the EMDX subnet:

```cmd
ERROR EMDX Subnet: Invalid JSON RPC response: "error code: 1020"
```

Is this due to some rate limit thing? Can you fix this on your RPC node?

**Comment by maxidev** [comment]
> @maxidev balance should be reflected as soon as it's transferred. I'm seeing this error in the logs for the EMDX subnet:
> 
> ```batchfile
> ERROR EMDX Subnet: Invalid JSON RPC response: "error code: 1020"
> ```
> 
> Is this due to some rate limit thing? Can you fix this on your RPC node?

thanks for the fast response, let me check ASAP and get back to you!

**Comment by maxidev** [comment]
@rajranjan0608  Can I ask what's the internal RPC call that the faucet is doing to get balance? because using our RPC en metamask and check for addrs balances works just fine, thank you very much!

**Comment by rajranjan0608** [comment]
@maxidev We are using the following [calls](https://github.com/ava-labs/avalanche-faucet/blob/main/vms/evm.ts#L242-L245) to recalibrate nonce and balance every 30 seconds.

```typescript
            [this.nonce, this.balance] = await Promise.all([
                this.web3.eth.getTransactionCount(this.account.address, 'latest'),
                this.web3.eth.getBalance(this.account.address),
            ])
```

**Comment by rajranjan0608** [comment]
Hey @maxidev, just checking on this if you find anything related to the above issue.

We might need to pause this integration until you guys are able to put in a fix. Thanks!

**Comment by maxidev** [comment]
Hey @rajranjan0608 thanks for the reply, weird thing is that as far as we can test, the RPC seems to be working just fine:
image

**Comment by rajranjan0608** [comment]
Yeah, it's weird. Probably your node client or provider (like Cloudflare) is treating the faucet as a bot/spam, and banning us from accessing the APIs. Would be great if you can configure your node provider.

**Pull request merged**
