### PR TITLE
Add Numbers Testnet

### PR DESCRIPTION
**Pull request by bafu**
Support Numbers Testnet's NUM token on Avalanche Faucet.

### CODE REVIEW

**Comment by bafu** [comment]
Hi Avalanche team,

Thanks for your time reviewing this PR.

Quick question: Where and how should I provide the faucet wallet for integrating it into Avalanche faucet?

Thanks!

**Comment by rajranjan0608** [comment]
Hi @bafu. Thanks for making this PR. We are going to integrate **Numbers Testnet** into our faucet. As a next step, please send some funds to the faucet address shown below. Thanks :)

```
0x2352D20fC81225c8ECD8f6FaA1B37F24FEd450c9
```

**Comment by bafu** [comment]
@rajranjan0608 I've sent the amounts to the testing and faucet wallets. Many thanks for your great support!

**Comment by rajranjan0608** [comment]
@bafu Here you go - https://faucet.avax.network/?subnet=num

**Comment by shc261392** [comment]
Hi @rajranjan0608 , the faucet seems to not work for me recently. I've tested it a few times and it never really send any NUM to my test wallet.

For example, I get the message `Transaction successful on Numbers Testnet!` and transaction hash `0xa135d623e217d8217dafa3a3c7f3ceeac51711087ec80bc344d358d2856335a2` on the faucet site, but the transaction is not found on the [explorer](https://testnet.num.network/tx/0xa135d623e217d8217dafa3a3c7f3ceeac51711087ec80bc344d358d2856335a2). When I use the RPC to get the transaction receipt using the hash, I also cannot find the transaction.

Any idea what might be the cause of the issue?
Thanks!

**Comment by rajranjan0608** [comment]
Hey @shc261392. The transaction hash is pre-calculated and sent to users even before issuing transactions. If any error occurred after issuing the transaction, then the transaction hash would not be of any use.

I'm seeing error logs to increase the max fee cap for the transactions to be more than 750 GWEI, which is currently set to 100 GWEI. These configs should generally be updated by the Subnet team (here @bafu) that integrated their faucet.

```
ERROR Numbers Testnet: Returned error: transaction underpriced: address 0x2352D20fC81225c8ECD8f6FaA1B37F24FEd450c9 have gas fee cap (100000000000) < pool minimum fee cap (750000000000)
```

cc: @bafu can you take a look and create a PR to update the fee config?

**Pull request merged**
